name: test
on:
  push:
    branches: [never]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    - name: Create Artifact
        run: echo "test" > test.txt

    - name: Upload Repository
        if: {{ $secrets.REPO_KEY && $secrets.REPO_USER && $secrets.REPO_SERVER}}
        uses:   wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: {{ $secrets.REPO_USER }}
          server: {{ $secrets.REPO_SERVER }}
          ssh_private_key: {{ $secrets.REPO_KEY }}
          local_path: './test.txt'
          remote_path: '/release/avnav-history-plugin/test'
