name: test
on:
  push:
    branches: [never]
  workflow_dispatch:

jobs:
  
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create Artifact
        run: echo "test" > test.txt
      - name: deps
        run: npm install ssh2-sftp-client
      - name: Upload Repository
        uses:  actions/github-script@v3
        with:
          REPO_KEY: '${{ secrets.REPO_KEY }}'
          REPO_SERVER: '${{ secrets.REPO_SERVER }}'
          REPO_USER: '${{ secrets.REPO_USER }}'
          FILE_NAME: 'test.txt'
          REMOTE_DIR: '/release/avnav-history-plugin/test'
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            let key=core.getInput('REPO_KEY')
            let user=core.getInput('REPO_USER')
            let server=core.getInput('REPO_SERVER')
            if (key && user && server){
              const upload=require(`${process.env.GITHUB_WORKSPACE}/.github/sftpUpload.js`);        
              let res=await upload(server ,user,key,`${process.env.GITHUB_WORKSPACE}/${core.getInput('FILE_NAME')}`,core.getInput('REMOTE_DIR'));
              if (res !== '') throw new Error(res);
            }
            else{
              console.log("secrets not set, skipping upload");
            }
            console.log("script done");
